<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\OutsideWalletAddress;
use Illuminate\Database\Seeder;

class OutsideWalletAddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $outside_wallet_addresses = array(
            array('currency_id' => '2','network_id' => '3','slug' => 'yutyasdfjbsmfasjkdfjasjkfd','public_address' => 'yutyasdfjbsmfasjkdfjasjkfd','desc' => '<p><span>A network refers to a system of interconnected elements or entities that communicate and interact with each other. In the realm of technology, a network commonly denotes the interconnection of computers, devices, or systems to facilitate the exchange of information and resources.</span></p>','input_fields' => '[{"type":"text","label":"trx_id","name":"trx_id","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}}]','status' => '1','created_at' => '2024-01-02 09:12:25','updated_at' => '2024-01-02 09:46:48'),
            array('currency_id' => '1','network_id' => '5','slug' => 'yutyasdfjbsmfasjkdfjasjkfdeee','public_address' => 'yutyasdfjbsmfasjkdfjasjkfdeee','desc' => '<p><span>A network refers to a system of interconnected elements or entities that communicate and interact with each other. In the realm of technology, a network commonly denotes the interconnection of computers, devices, or systems to facilitate the exchange of information and resources.</span></p>','input_fields' => '[{"type":"file","label":"Screenshot","name":"screenshot","required":true,"validation":{"max":"10","mimes":["jpg","jpeg","png"],"min":0,"options":[],"required":true}}]','status' => '1','created_at' => '2024-01-02 09:36:35','updated_at' => '2024-01-02 09:47:02'),
            array('currency_id' => '1','network_id' => '4','slug' => 'yutyasdfjbsmfasjkdfjasjkfdrrrrdfsdf','public_address' => 'yutyasdfjbsmfasjkdfjasjkfdrrrrdfsdf','desc' => '<p><span>A network refers to a system of interconnected elements or entities that communicate and interact with each other. In the realm of technology, a network commonly denotes the interconnection of computers, devices, or systems to facilitate the exchange of information and resources.&nbsp;</span><br><span>Currency is a medium of exchange that facilitates trade and commerce, serving as a unit of account and store of value. Traditionally, currencies were physical objects like coins or paper money, but in the modern era, digital currencies have gained prominence.&nbsp;</span></p>','input_fields' => '[{"type":"file","label":"Screenshot","name":"screenshot","required":true,"validation":{"max":"10","mimes":["jpg","jpeg","png"],"min":0,"options":[],"required":true}},{"type":"text","label":"trx_id","name":"trx_id","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}}]','status' => '1','created_at' => '2024-01-02 09:41:27','updated_at' => '2024-01-02 09:41:27'),
            array('currency_id' => '2','network_id' => '2','slug' => 'yutyasdfjbsmfasjkdfjasjkfdbdtfjkldfgkl','public_address' => 'yutyasdfjbsmfasjkdfjasjkfdbdtfjkldfgkl','desc' => '<p><span>Currency is a medium of exchange that facilitates trade and commerce, serving as a unit of account and store of value. Traditionally, currencies were physical objects like coins or paper money, but in the modern era, digital currencies have gained prominence.&nbsp;</span><br><span>A network refers to a system of interconnected elements or entities that communicate and interact with each other.&nbsp;</span></p>','input_fields' => '[{"type":"text","label":"trx_id","name":"trx_id","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshot","name":"screenshot","required":true,"validation":{"max":"10","mimes":["jpg","jpeg","png"],"min":0,"options":[],"required":true}}]','status' => '1','created_at' => '2024-01-02 09:43:23','updated_at' => '2024-01-02 09:43:23'),
            array('currency_id' => '3','network_id' => '5','slug' => 'yutyasdfjbsmfasjkdfjasjkfdrrrrdfsdfsklkmcnmkxdjih','public_address' => 'yutyasdfjbsmfasjkdfjasjkfdrrrrdfsdfsklkmcnmkxdjih','desc' => '<p><span>A network refers to a system of interconnected elements or entities that communicate and interact with each other.&nbsp;</span></p><p><span>Currency is a medium of exchange that facilitates trade and commerce, serving as a unit of account and store of value. Traditionally, currencies were physical objects like coins or paper money, but in the modern era, digital currencies have gained prominence.&nbsp;</span></p>','input_fields' => '[{"type":"text","label":"trx_id","name":"trx_id","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshot","name":"screenshot","required":true,"validation":{"max":"10","mimes":["jpg","jpeg","png"],"min":0,"options":[],"required":true}}]','status' => '1','created_at' => '2024-01-02 09:45:07','updated_at' => '2024-01-02 09:45:07'),
            array('currency_id' => '4','network_id' => '4','slug' => 'yutyasdfjbsmfasjkdfjasjkfdgsjhdfgsdf','public_address' => 'yutyasdfjbsmfasjkdfjasjkfdgsjhdfgsdf','desc' => '<p><span>Currency is a medium of exchange that facilitates trade and commerce, serving as a unit of account and store of value. Traditionally, currencies were physical objects like coins or paper money, but in the modern era, digital currencies have gained prominence.&nbsp;</span></p><p><span>A network refers to a system of interconnected elements or entities that communicate and interact with each other. In the realm of technology, a network commonly denotes the interconnection of computers, devices, or systems to facilitate the exchange of information and resources.</span></p>','input_fields' => '[{"type":"text","label":"trx_id","name":"trx_id","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"file","label":"Screenshot","name":"screenshot","required":true,"validation":{"max":"10","mimes":["jpg","jpeg","png"],"min":0,"options":[],"required":true}}]','status' => '1','created_at' => '2024-01-02 09:46:33','updated_at' => '2024-01-02 09:46:33')
        );
        OutsideWalletAddress::insert($outside_wallet_addresses);
    }
}
